<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {   
        $this->call(AchievementsTableSeeder::class);
        $this->call(AchievementsTalentsTableSeeder::class);
        $this->call(BansTableSeeder::class);
        $this->call(BotsTableSeeder::class);
        $this->call(CalendarRewardsTableSeeder::class);
        $this->call(CalendarRewardsClaimedTableSeeder::class);
        $this->call(CameraWebTableSeeder::class);
        $this->call(CatalogClothingTableSeeder::class);
        $this->call(CatalogClubOffersTableSeeder::class);
        $this->call(CatalogFeaturedPagesTableSeeder::class);
        $this->call(CatalogItemsTableSeeder::class);
        $this->call(CatalogItemsBcTableSeeder::class);
        $this->call(CatalogTargetOffersTableSeeder::class);
        $this->call(ChatlogsPrivateTableSeeder::class);
        $this->call(ChatlogsRoomTableSeeder::class);
        $this->call(CmsNewsTableSeeder::class);
        $this->call(CmsNewsLikeTableSeeder::class);
        $this->call(CmsNewsMessageTableSeeder::class);
        $this->call(CommandlogsTableSeeder::class);
        $this->call(CraftingAltarsRecipesTableSeeder::class);
        $this->call(CraftingRecipesTableSeeder::class);
        $this->call(CraftingRecipesIngredientsTableSeeder::class);
        $this->call(EmulatorErrorsTableSeeder::class);
        $this->call(EmulatorSettingsTableSeeder::class);
        $this->call(EmulatorTextsTableSeeder::class);
        $this->call(GiftWrappersTableSeeder::class);
        $this->call(GroupsItemsTableSeeder::class);
        $this->call(GuildsTableSeeder::class);
        $this->call(GuildsElementsTableSeeder::class);
        $this->call(GuildsForumsCommentsTableSeeder::class);
        $this->call(GuildsForumsThreadsTableSeeder::class);
        $this->call(GuildsMembersTableSeeder::class);
        $this->call(GuildForumViewsTableSeeder::class);
        $this->call(HotelviewNewsTableSeeder::class);
        $this->call(ItemsTableSeeder::class);
        $this->call(ItemsBaseTableSeeder::class);
        $this->call(ItemsCrackableTableSeeder::class);
        $this->call(ItemsHighscoreDataTableSeeder::class);
        $this->call(ItemsHoppersTableSeeder::class);
        $this->call(ItemsPresentsTableSeeder::class);
        $this->call(ItemsTeleportsTableSeeder::class);
        $this->call(LogsHcPaydayTableSeeder::class);
        $this->call(LogsShopPurchasesTableSeeder::class);
        $this->call(MarketplaceItemsTableSeeder::class);
        $this->call(MessengerFriendrequestsTableSeeder::class);
        $this->call(MessengerFriendshipsTableSeeder::class);
        $this->call(MessengerOfflineTableSeeder::class);
        $this->call(NamechangeLogTableSeeder::class);
        $this->call(RoomRightsTableSeeder::class);
        $this->call(NavigatorFilterTableSeeder::class);
        $this->call(RoomTradeLogTableSeeder::class);
        $this->call(NavigatorFlatcatsTableSeeder::class);
        $this->call(RoomTradeLogItemsTableSeeder::class);
        $this->call(NavigatorPubliccatsTableSeeder::class);
        $this->call(RoomTraxTableSeeder::class);
        $this->call(NavigatorPublicsTableSeeder::class);
        $this->call(RoomTraxPlaylistTableSeeder::class);
        $this->call(NuxGiftsTableSeeder::class);
        $this->call(RoomVotesTableSeeder::class);
        $this->call(OldGuildsForumsTableSeeder::class);
        $this->call(RoomWordfilterTableSeeder::class);
        $this->call(OldGuildsForumsCommentsTableSeeder::class);
        $this->call(SanctionsTableSeeder::class);
        $this->call(PermissionsTableSeeder::class);
        $this->call(SanctionLevelsTableSeeder::class);
        $this->call(PetActionsTableSeeder::class);
        $this->call(SoundtracksTableSeeder::class);
        $this->call(PetBreedingTableSeeder::class);
        $this->call(SpecialEnablesTableSeeder::class);
        $this->call(PetBreedingRacesTableSeeder::class);
        $this->call(StaffapplicationTableSeeder::class);
        $this->call(PetBreedsTableSeeder::class);
        $this->call(SupportCfhCategoriesTableSeeder::class);
        $this->call(PetCommandsTableSeeder::class);
        $this->call(SupportCfhTopicsTableSeeder::class);
        $this->call(PetCommandsDataTableSeeder::class);
        $this->call(SupportIssuePresetsTableSeeder::class);
        $this->call(PetDrinksTableSeeder::class);
        $this->call(SupportPresetsTableSeeder::class);
        $this->call(PetFoodsTableSeeder::class);
        $this->call(SupportTicketsTableSeeder::class);
        $this->call(PetItemsTableSeeder::class);
        $this->call(TeamsTableSeeder::class);
        $this->call(PetVocalsTableSeeder::class);
        $this->call(TraxPlaylistTableSeeder::class);
        $this->call(PollsTableSeeder::class);
        $this->call(PollsAnswersTableSeeder::class);
        $this->call(PollsQuestionsTableSeeder::class);
        $this->call(RanksTableSeeder::class);
        $this->call(UotwTableSeeder::class);
        $this->call(RecyclerPrizesTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(ReferrerTableSeeder::class);
        $this->call(UsersAchievementsTableSeeder::class);
        $this->call(ReferrerbankTableSeeder::class);
        $this->call(UsersAchievementsQueueTableSeeder::class);
        $this->call(ResetpasswordTableSeeder::class);
        $this->call(UsersBadgesTableSeeder::class);
        $this->call(RoomsTableSeeder::class);
        $this->call(UsersClothingTableSeeder::class);
        $this->call(RoomBansTableSeeder::class);
        $this->call(UsersCurrencyTableSeeder::class);
        $this->call(RoomEnterLogTableSeeder::class);
        $this->call(UsersEffectsTableSeeder::class);
        $this->call(RoomGameScoresTableSeeder::class);
        $this->call(UsersFavoriteRoomsTableSeeder::class);
        $this->call(RoomModelsTableSeeder::class);
        $this->call(UsersIgnoredTableSeeder::class);
        $this->call(RoomModelsCustomTableSeeder::class);
        $this->call(UsersLikeTableSeeder::class);
        $this->call(RoomMutesTableSeeder::class);
        $this->call(UsersNavigatorSettingsTableSeeder::class);
        $this->call(RoomPromotionsTableSeeder::class);
        $this->call(UsersPetsTableSeeder::class);
        $this->call(UsersRecipesTableSeeder::class);
        $this->call(UsersSavedSearchesTableSeeder::class);
        $this->call(UsersSettingsTableSeeder::class);
        $this->call(UsersSubscriptionsTableSeeder::class);
        $this->call(UsersTargetOfferPurchasesTableSeeder::class);
        $this->call(UsersWardrobeTableSeeder::class);
        $this->call(UserSessionLogTableSeeder::class);
        $this->call(UserWindowSettingsTableSeeder::class);
        $this->call(VouchersTableSeeder::class);
        $this->call(VoucherHistoryTableSeeder::class);
        $this->call(WiredRewardsGivenTableSeeder::class);
        $this->call(WordfilterTableSeeder::class);
        $this->call(WordfilterCharactersTableSeeder::class);
        $this->call(YoutubePlaylistsTableSeeder::class); 
    }
}