<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsCrackableTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('items_crackable')->delete();
        
        \DB::table('items_crackable')->insert(array (
            0 => 
            array (
                'achievement_cracked' => 'EggMaster',
                'achievement_tick' => 'EggCracker',
                'count' => 1000,
                'item_id' => 4986,
                'item_name' => 'easter13_egg_0',
                'prizes' => '1975:11;21:11;26:11;28:11;36:11;47:11;249:11;253:11;1759:11',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            1 => 
            array (
                'achievement_cracked' => 'EggMaster',
                'achievement_tick' => 'EggCracker',
                'count' => 20000,
                'item_id' => 4987,
                'item_name' => 'easter13_egg_3',
                'prizes' => '5009:20;5000:40;5006:40',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            2 => 
            array (
                'achievement_cracked' => 'EggMaster',
                'achievement_tick' => 'EggCracker',
                'count' => 5000,
                'item_id' => 4988,
                'item_name' => 'easter13_egg_1',
                'prizes' => '5004:25;5005:25;5008:25;5010:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            3 => 
            array (
                'achievement_cracked' => 'EggMaster',
                'achievement_tick' => 'EggCracker',
                'count' => 10000,
                'item_id' => 4989,
                'item_name' => 'easter13_egg_2',
                'prizes' => '5001:25;5002:25;5007:25;5001:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            4 => 
            array (
                'achievement_cracked' => 'CrystalLegend',
                'achievement_tick' => 'CrystalCracker',
                'count' => 1500000,
                'item_id' => 5102,
                'item_name' => 'mystics_crystal_l',
                'prizes' => '5101:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            5 => 
            array (
                'achievement_cracked' => 'PinataBreaker',
                'achievement_tick' => 'PinataWhacker',
                'count' => 100,
                'item_id' => 5985,
                'item_name' => 'hblooza14_pinata2',
                'prizes' => '5996:60;6006:30;6017:10',
                'required_effect' => 158,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            6 => 
            array (
                'achievement_cracked' => 'PinataBreaker',
                'achievement_tick' => 'PinataWhacker',
                'count' => 100,
                'item_id' => 5990,
                'item_name' => 'hblooza14_pinata1',
                'prizes' => '5989:60;6007:30;6005:10',
                'required_effect' => 158,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            7 => 
            array (
                'achievement_cracked' => 'PinataBreaker',
                'achievement_tick' => 'PinataWhacker',
                'count' => 100,
                'item_id' => 6001,
                'item_name' => 'hblooza14_pinata3',
                'prizes' => '6003:60;6021:30;5999:10',
                'required_effect' => 158,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            8 => 
            array (
                'achievement_cracked' => 'PinataBreaker',
                'achievement_tick' => 'PinataWhacker',
                'count' => 100,
                'item_id' => 6028,
                'item_name' => 'hblooza14_pinata4',
                'prizes' => '5978:60;5977:30;5980:10',
                'required_effect' => 158,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            9 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8193,
                'item_name' => 'habbo15_rare_crackable',
                'prizes' => '8222:7;8221:7;8220:6;8219:7;8218:6;8217:7;8216:6;8215:7;8214:6;8213:7;8212:6;8211:7;8210:6;8209:7;8208:7',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            10 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8201,
                'item_name' => 'habbo15_crackable',
                'prizes' => '8193:1;8201:9;6024:10;6022:10;9325:6;9326:6;8236:6;8224:6;179:6;8239:6;8240:6;3134:6;4275:6;4246:6;46220:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            11 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8439,
                'item_name' => 'habbo15_pumpkin2',
                'prizes' => '6191:20;8384:16;8380:16;4738:16;5002:16;8401:16',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            12 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8438,
                'item_name' => 'habbo15_pumpkin1',
                'prizes' => '174:5;4268:5;3294:5;4292:5;6178:5;228:5;179:5;208:5;209:5;210:5;3233:5;6153:5;2102:5;4083:5;2946:5;5300:5;4309:5;177:5;3189:5;5869:5',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            13 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8451,
                'item_name' => 'gold_rare_crackable',
                'prizes' => '8443:5;8458:5;8457:5;8456:5;8455:5;8454:5;8453:5;8452:6;8450:6;8449:6;8448:6;8447:6;8446:5;8445:6;8444:6;8442:6;8441:6;46320:6',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            14 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 10,
                'item_id' => 8881,
                'item_name' => 'easter_r16_crackable',
                'prizes' => '8880:20;8882:20;8884:20;8886:20;46360:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            15 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8918,
                'item_name' => 'jungle_c16_flowerd2',
                'prizes' => '8919:25;8918:25;8951:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            16 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8919,
                'item_name' => 'jungle_c16_flowerd1',
                'prizes' => '8919:25;8918:25;8951:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            17 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8926,
                'item_name' => 'jungle_c16_flowerc3',
                'prizes' => '8983:25;8968:25;8926:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            18 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8948,
                'item_name' => 'jungle_c16_flowera3',
                'prizes' => '8975:25;8987:25;8948:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            19 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8951,
                'item_name' => 'jungle_c16_flowerd3',
                'prizes' => '8919:25;8918:25;8951:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            20 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8968,
                'item_name' => 'jungle_c16_flowerc2',
                'prizes' => '8983:25;8968:25;8926:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            21 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8975,
                'item_name' => 'jungle_c16_flowera1',
                'prizes' => '8975:25;8987:25;8948:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            22 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8977,
                'item_name' => 'jungle_c16_flowerb3',
                'prizes' => '8982:25;8981:25;8977:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            23 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8981,
                'item_name' => 'jungle_c16_flowerb2',
                'prizes' => '8982:25;8981:25;8977:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            24 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8982,
                'item_name' => 'jungle_c16_flowerb1',
                'prizes' => '8982:25;8981:25;8977:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            25 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8983,
                'item_name' => 'jungle_c16_flowerc1',
                'prizes' => '8983:25;8968:25;8926:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            26 => 
            array (
                'achievement_cracked' => 'Horticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 8987,
                'item_name' => 'jungle_c16_flowera2',
                'prizes' => '8975:25;8987:25;8948:25;8940:25',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            27 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8993,
                'item_name' => 'bonusbag16_1',
                'prizes' => '8350:9;8351:8;8352:8;8353:8;8354:9;8355:9;8356:8;8357:8;8358:9;8359:8;8360:8;8361:8',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            28 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8994,
                'item_name' => 'bonusbag16_2',
                'prizes' => '8628:10;8629:10;8630:10;8631:10;8887:10;8888:10;8889:10;8890:10;889:101;8892:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            29 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9134,
                'item_name' => 'hhistory_r16_crackable',
                'prizes' => '9131:6;9132:8;9133:6;9135:7;9136:6;9137:7;9138:6;9139:7;9140:6;9141:7;9142:6;9143:7;9144:6;9145:8;9146:6',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            30 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 9154,
                'item_name' => 'hween_r16_crackable2',
                'prizes' => '9178:30;9156:30;9171:15;9197:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            31 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 9164,
                'item_name' => 'hween_c16_crackable1',
                'prizes' => '9158:50;9188:35;9191:15',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            32 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9230,
                'item_name' => 'xmas_c16_stocking',
                'prizes' => '9254:5;9218:5;9217:5;9216:5;8499:5;8484:5;6253:5;5496:5;4330:5;4315:5;4304:5;4293:5;4291:5;4287:5;3740:5;3313:5;2064:5;215:5;214:5;212:5',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            33 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9281,
                'item_name' => 'bonusbag16_3',
                'prizes' => '8893:9;8894:8;8895:8;8896:8;8897:9;8898:9;9282:8;9283:8;9284:9;9285:8;9286:8;9287:8',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            34 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 9324,
                'item_name' => 'bc_gift_31days',
                'prizes' => '',
                'required_effect' => 0,
                'subscription_duration' => 31,
                'subscription_type' => 'bc',
            ),
            35 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9325,
                'item_name' => 'hc_gift_14days',
                'prizes' => '',
                'required_effect' => 0,
                'subscription_duration' => 14,
                'subscription_type' => 'hc',
            ),
            36 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9326,
                'item_name' => 'hc_gift_31days',
                'prizes' => '',
                'required_effect' => 0,
                'subscription_duration' => 31,
                'subscription_type' => 'hc',
            ),
            37 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 9327,
                'item_name' => 'bc_gift_14days',
                'prizes' => '',
                'required_effect' => 0,
                'subscription_duration' => 14,
                'subscription_type' => 'bc',
            ),
            38 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9408,
                'item_name' => 'easter_c17_floweringbush',
                'prizes' => '9444:34;9431:33;9434:33',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            39 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 9416,
                'item_name' => 'easter_c17_egg',
                'prizes' => '9457:10;5838:9;3424:9;9411:9;8583:9;8595:9;3412:9;3921:9;7972:9;5834:9;8252:9',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            40 => 
            array (
                'achievement_cracked' => 'Farmer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9425,
                'item_name' => 'easter_c17_leafsprout',
                'prizes' => '9436:100',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            41 => 
            array (
                'achievement_cracked' => 'Farmer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9433,
                'item_name' => 'easter_c17_sapling',
                'prizes' => '9408:100',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            42 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9445,
                'item_name' => 'easter_c17_seeds',
                'prizes' => '9433:50;9425:50',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            43 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9447,
                'item_name' => 'easter_c17_seedbag',
                'prizes' => '9445:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            44 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9461,
                'item_name' => 'bonusbag17_1',
                'prizes' => '9348:12;9347:13;9346:12;9345:13;9344:12;9343:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            45 => 
            array (
                'achievement_cracked' => 'Restorer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9463,
                'item_name' => 'santorini_c17_artefact4',
                'prizes' => '9492:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            46 => 
            array (
                'achievement_cracked' => 'Restorer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9467,
                'item_name' => 'santorini_c17_artefact3',
                'prizes' => '9472:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            47 => 
            array (
                'achievement_cracked' => 'Restorer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9475,
                'item_name' => 'santorini_c17_artefact5',
                'prizes' => '9479:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            48 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9477,
                'item_name' => 'santorini_r17_chest',
                'prizes' => '9463:20;9467:20;9475:20;9480:20;9502:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            49 => 
            array (
                'achievement_cracked' => 'Restorer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9480,
                'item_name' => 'santorini_c17_artefact1',
                'prizes' => '9482:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            50 => 
            array (
                'achievement_cracked' => 'Restorer',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9502,
                'item_name' => 'santorini_c17_artefact2',
                'prizes' => '9470:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            51 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9549,
                'item_name' => 'bonusbag17_2',
                'prizes' => '9366:12;9365:13;9364:12;9363:13;9362:12;9361:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            52 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9667,
                'item_name' => 'hhistory_r17_crackable',
                'prizes' => '9656:6;9657:6;9658:6;9659:7;9660:6;9661:6;9662:6;9663:7;9664:6;9665:6;9666:6;9668:7;9669:6;9670:6;9671:6;9672:7',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            53 => 
            array (
                'achievement_cracked' => 'flamingknight',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 9753,
                'item_name' => 'hween_c17_flamingknight',
                'prizes' => '9738:20;9733:20;9739:20;9760:20;9727:10;9734:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            54 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9763,
                'item_name' => 'bonusbag17_3',
                'prizes' => '9360:12;9359:13;9358:12;9357:13;9356:12;9355:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            55 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9764,
                'item_name' => 'bonusbag17_4',
                'prizes' => '9354:12;9353:13;9352:12;9351:13;9350:12;9349:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            56 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9808,
                'item_name' => 'xmas_c17_book',
                'prizes' => '9790:17;9793:16;9801:17;9829:17;9833:16;9842:17',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            57 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9867,
                'item_name' => 'bonusbag18_3',
                'prizes' => '9866:12;9865:13;9864:12;9863:13;9862:12;9861:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            58 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9868,
                'item_name' => 'bonusbag18_2',
                'prizes' => '9874:12;9873:13;9872:12;9871:13;9870:12;9869:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            59 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9875,
                'item_name' => 'bonusbag18_4',
                'prizes' => '9882:12;9881:13;9880:12;9879:13;9878:12;9877:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            60 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9876,
                'item_name' => 'bonusbag18_1',
                'prizes' => '9888:12;9887:13;9886:12;9885:13;9884:12;9883:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            61 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9896,
                'item_name' => 'ny18_crackable',
                'prizes' => '9891:10;9889:15;9890:15;9892:15;9893:15;9894:15;9895:15',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            62 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9961,
                'item_name' => 'easter_c18_snowdrop3',
                'prizes' => '10017:20;9969:20;10021:20;9961:20;9986:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            63 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9963,
                'item_name' => 'easter_c18_lupin1',
                'prizes' => '9963:20;9969:20;10002:20;9976:20;9978:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            64 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9965,
                'item_name' => 'easter_c18_tulip2',
                'prizes' => '9997:20;9969:20;9965:20;9972:20;10006:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            65 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9966,
                'item_name' => 'easter_c18_seedpackrose',
                'prizes' => '10022:25;9994:25;9971:25;9983:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            66 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9970,
                'item_name' => 'easter_c18_seedpacktulip',
                'prizes' => '9997:25;9965:25;9972:25;10006:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            67 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9971,
                'item_name' => 'easter_c18_rose3',
                'prizes' => '10022:20;9971:20;9969:20;9983:20;9994:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            68 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9972,
                'item_name' => 'easter_c18_tulip3',
                'prizes' => '9997:20;9969:20;9965:20;9972:20;10006:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            69 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9976,
                'item_name' => 'easter_c18_lupin3',
                'prizes' => '9963:20;9969:20;10002:20;9976:20;9978:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            70 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9978,
                'item_name' => 'easter_c18_lupin4',
                'prizes' => '9963:20;9969:20;10002:20;9976:20;9978:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            71 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9982,
                'item_name' => 'easter_c18_seedpacksnowdrop',
                'prizes' => '10017:25;10021:25;9961:25;9986:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            72 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9983,
                'item_name' => 'easter_c18_rose4',
                'prizes' => '10022:20;9971:20;9969:20;9983:20;9994:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            73 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9986,
                'item_name' => 'easter_c18_snowdrop4',
                'prizes' => '10017:20;9969:20;10021:20;9961:20;9986:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            74 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9994,
                'item_name' => 'easter_c18_rose2',
                'prizes' => '10022:20;9971:20;9969:20;9983:20;9994:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            75 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 9997,
                'item_name' => 'easter_c18_tulip1',
                'prizes' => '9997:20;9969:20;9965:20;9972:20;10006:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            76 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 10002,
                'item_name' => 'easter_c18_lupin2',
                'prizes' => '9963:20;9969:20;10002:20;9976:20;9978:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            77 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 10006,
                'item_name' => 'easter_c18_tulip4',
                'prizes' => '9997:20;9969:20;9965:20;9972:20;10006:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            78 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10013,
                'item_name' => 'easter_c18_seedpacklupin',
                'prizes' => '9963:25;10002:25;9976:25;9978:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            79 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 10017,
                'item_name' => 'easter_c18_snowdrop1',
                'prizes' => '10017:20;9969:20;10021:20;9961:20;9986:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            80 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 10021,
                'item_name' => 'easter_c18_snowdrop2',
                'prizes' => '10017:20;9969:20;10021:20;9961:20;9986:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            81 => 
            array (
                'achievement_cracked' => 'AdvancedHorticulturist',
                'achievement_tick' => '',
                'count' => 12,
                'item_id' => 10022,
                'item_name' => 'easter_c18_rose1',
                'prizes' => '10022:20;9971:20;9969:20;9983:20;9994:20',
                'required_effect' => 192,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            82 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10070,
                'item_name' => 'coralking_c18_treasurechest',
                'prizes' => '10062:4;10065:4;10069:4;10077:4;10080:4;10081:4;10084:4;10086:4;10089:4;10100:4;10104:4;10108:4;10110:4;10118:4;10119:4;10072:8;10099:7;10111:8;10117:7;10093:5;10113:5',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            83 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10078,
                'item_name' => 'coralking_r18_goldenchest',
                'prizes' => '10072:18;10099:17;10111:18;10117:17;10093:15;10113:15',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            84 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10170,
                'item_name' => 'tokyo_c18_gacha',
                'prizes' => '10132:10;10133:10;10139:10;10144:10;10152:10;10154:10;10155:10;10167:10;10168:10;10185:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            85 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10212,
                'item_name' => 'hhistory_r18_crackable',
                'prizes' => '10206:6;10207:6;10208:6;10209:7;10210:6;10211:6;10213:6;10214:7;10215:6;10216:6;10217:6;10218:7;10219:6;10220:6;10221:6;10222:7',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            86 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10322,
                'item_name' => 'diamond_c18_giftbox',
                'prizes' => '10323:45;10324:45;10321:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            87 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10341,
                'item_name' => 'xmas_c18_doll10',
                'prizes' => '10349:80;10394:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            88 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10343,
                'item_name' => 'xmas_c18_doll8',
                'prizes' => '10387:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            89 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10349,
                'item_name' => 'xmas_c18_doll6',
                'prizes' => '10384:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            90 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10352,
                'item_name' => 'xmas_c18_doll5',
                'prizes' => '10378:80;10394:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            91 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10370,
                'item_name' => 'xmas_c18_doll3',
                'prizes' => '10398:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            92 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10371,
                'item_name' => 'xmas_c18_doll2',
                'prizes' => '10370:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            93 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10378,
                'item_name' => 'xmas_c18_doll1',
                'prizes' => '10371:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            94 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10384,
                'item_name' => 'xmas_c18_doll7',
                'prizes' => '10343:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            95 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10387,
                'item_name' => 'xmas_c18_doll9',
                'prizes' => '10341:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            96 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10398,
                'item_name' => 'xmas_c18_doll4',
                'prizes' => '10352:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            97 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10414,
                'item_name' => 'ny_r18_crackable',
                'prizes' => '10409:12;10410:13;10411:12;10412:13;10415:12;10416:13;10417:12;10418:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            98 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 10487,
                'item_name' => 'easter_c19_babyent',
                'prizes' => '10516:75;10495:25',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            99 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10497,
                'item_name' => 'easter_c19_book1',
                'prizes' => '10517:45;10535:45;10522:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            100 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10498,
                'item_name' => 'easter_c19_book3',
                'prizes' => '10532:45;10513:45;10494:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            101 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10501,
                'item_name' => 'easter_c19_book2',
                'prizes' => '10488:45;10524:45;10504:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            102 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10505,
                'item_name' => 'easter_c19_book4',
                'prizes' => '10530:45;10538:45;10523:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            103 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 10510,
                'item_name' => 'easter_c19_babyhippogriff',
                'prizes' => '10541:75;10537:25',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            104 => 
            array (
                'achievement_cracked' => 'EasterCreatures',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 10512,
                'item_name' => 'easter_c19_forrestegg',
                'prizes' => '10510:50;10487:35;10529:15',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            105 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10518,
                'item_name' => 'easter_c19_ancientbook',
                'prizes' => '10497:25;10501:25;10498:25;10505:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            106 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 20,
                'item_id' => 10529,
                'item_name' => 'easter_c19_babykelpie',
                'prizes' => '10484:75;10528:25',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            107 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10543,
                'item_name' => 'bonusbag19_1',
                'prizes' => '10549:12;10548:13;10547:12;10546:13;10545:12;10544:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            108 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10572,
                'item_name' => 'booster_c19_box1',
                'prizes' => '10568:10;10563:10;10559:10;10557:10;10555:10;10551:10;10558:10;10554:10;10562:10;10562:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            109 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10573,
                'item_name' => 'booster_c19_box2',
                'prizes' => '10568:10;10563:10;10559:10;10557:10;10555:10;10551:10;10558:10;10554:10;10562:10;10562:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            110 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10665,
                'item_name' => 'bonusbag19_2',
                'prizes' => '10671:12;10670:13;10669:12;10668:13;10667:12;10666:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            111 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10800,
                'item_name' => 'hween_c19_witchsatchel',
                'prizes' => '10787:12;10791:13;10798:12;10812:13;10825:13;10826:12;10829:13;10824:12',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            112 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10833,
                'item_name' => 'bonusbag19_3',
                'prizes' => '10839:12;10838:13;10837:12;10836:13;10835:12;10834:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            113 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10901,
                'item_name' => 'xmas_c19_box3',
                'prizes' => '10931:50;10884:50',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            114 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10916,
                'item_name' => 'xmas_c19_box2',
                'prizes' => '10901:50;10907:50',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            115 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10928,
                'item_name' => 'xmas_c19_box6',
                'prizes' => '10944:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            116 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10931,
                'item_name' => 'xmas_c19_box4',
                'prizes' => '10936:50;10940:50',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            117 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10936,
                'item_name' => 'xmas_c19_box5',
                'prizes' => '10928:50;10930:50',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            118 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 10943,
                'item_name' => 'xmas_c19_box1',
                'prizes' => '10916:50;10902:50',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            119 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10951,
                'item_name' => 'bonusbag19_4',
                'prizes' => '10950:12;10949:13;10948:12;10947:13;10946:12;10945:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            120 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10970,
                'item_name' => 'ny_r19_crackable',
                'prizes' => '10968:13;10966:12;10967:13;10969:12;10962:13;10963:12;10964:13;10965:12',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            121 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11017,
                'item_name' => 'bonusbag20_1',
                'prizes' => '11023:12;11022:13;11021:12;11020:13;11019:12;11018:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            122 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11030,
                'item_name' => 'bonusbag20_3',
                'prizes' => '11036:12;11035:13;11034:12;11033:13;11033:12;11031:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            123 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11043,
                'item_name' => 'bonusbag20_2',
                'prizes' => '11029:12;11028:13;11027:12;11026:13;11025:12;11024:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            124 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11044,
                'item_name' => 'bonusbag20_4',
                'prizes' => '11042:12;11041:13;11040:12;11039:13;11038:12;11037:13;9326:12;2065:13',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            125 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11048,
                'item_name' => 'booster_c20_box',
                'prizes' => '11069:15;11062:14;11076:9;11065:9;11056:8;11070:8;11059:7;11058:6;11061:6;11073:6;11054:5;11067:5;11046:2',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            126 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11081,
                'item_name' => 'easter_c20_darkrock',
                'prizes' => '11104:31;11093:31;11105:31;11083:7',
                'required_effect' => 183,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            127 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11083,
                'item_name' => 'easter_c20_darkprize4',
                'prizes' => '11114:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            128 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11093,
                'item_name' => 'easter_c20_darkprize2',
                'prizes' => '11116:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            129 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11104,
                'item_name' => 'easter_c20_darkprize3',
                'prizes' => '11138:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            130 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11105,
                'item_name' => 'easter_c20_darkprize1',
                'prizes' => '11127:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            131 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11120,
                'item_name' => 'easter_c20_lightprize3',
                'prizes' => '11132:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            132 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11124,
                'item_name' => 'easter_c20_lightprize2',
                'prizes' => '11130:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            133 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11126,
                'item_name' => 'easter_c20_lightrock',
                'prizes' => '11120:31;11124:31;11135:31;11134:7',
                'required_effect' => 183,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            134 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11134,
                'item_name' => 'easter_c20_lightprize4',
                'prizes' => '11082:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            135 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11135,
                'item_name' => 'easter_c20_lightprize1',
                'prizes' => '11089:100',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            136 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11148,
                'item_name' => 'spa_c20_crackable1A',
                'prizes' => '11160:10;11153:25;11154:25;11167:20;11165:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            137 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11166,
                'item_name' => 'spa_c20_crackable2A',
                'prizes' => '11149:10;11162:25;11147:25;11156:20;11158:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            138 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11210,
                'item_name' => 'india_c20_blueprint',
                'prizes' => '11195:20;11190:20;11179:20;11172:20;11212:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            139 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 14,
                'item_id' => 5332,
                'item_name' => 'mystics_crystal',
                'prizes' => '179:100',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            140 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 10626,
                'item_name' => 'fest_c19_bprintcrackable',
                'prizes' => '10600:25;10606:25;10614:25;10636:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            141 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11308,
                'item_name' => 'habbo20_r20_crackable',
                'prizes' => '11327:1;11314:2;11325:4;11315:4;11313:4;11330:6;11329:6;11320:6;11323:7;11318:7;11317:7;11328:9;11324:9;11321:9;11319:9;11322:10',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            142 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11309,
                'item_name' => 'habbo20_c20_crackable',
                'prizes' => '11309:3;11308:1;6281:6;6292:10;8583:10;8335:10;10481:12;7843:12;8589:12;10821:12;8526:12',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            143 => 
            array (
                'achievement_cracked' => 'PinataBreaker',
                'achievement_tick' => 'PinataWhacker',
                'count' => 100,
                'item_id' => 5194,
                'item_name' => 'hblooza_pinata1',
                'prizes' => '5183:17;5192:16;5182:17;5191:17;5190:16;5184:17',
                'required_effect' => 158,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            144 => 
            array (
                'achievement_cracked' => 'PinataBreaker',
                'achievement_tick' => 'PinataWhacker',
                'count' => 100,
                'item_id' => 5193,
                'item_name' => 'hblooza_pinata2',
                'prizes' => '5188:20;5185:20;5187:20;5189:20;5186:20',
                'required_effect' => 158,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            145 => 
            array (
                'achievement_cracked' => 'CreatureRearer',
                'achievement_tick' => '',
                'count' => 24,
                'item_id' => 9214,
                'item_name' => 'xmas_c16_creature7',
                'prizes' => '9256:50;9246:50',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            146 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 24,
                'item_id' => 9232,
                'item_name' => 'xmas_c16_egg',
                'prizes' => '9214:33;9238:33;9251:34',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            147 => 
            array (
                'achievement_cracked' => 'CreatureRearer',
                'achievement_tick' => '',
                'count' => 24,
                'item_id' => 9238,
                'item_name' => 'xmas_c16_creature1',
                'prizes' => '9211:50;9258:50',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            148 => 
            array (
                'achievement_cracked' => 'CreatureRearer',
                'achievement_tick' => '',
                'count' => 24,
                'item_id' => 9251,
                'item_name' => 'xmas_c16_creature4',
                'prizes' => '9224:50;9242:50',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            149 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 8548,
                'item_name' => 'ny16_crackable',
                'prizes' => '8545:10;8543:15;8546:15;8541:20;8540:20;8542:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            150 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 9288,
                'item_name' => 'ny17_crackable',
                'prizes' => '9289:5;9291:15;9292:15;9293:20;9294:20;9295:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            151 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 30,
                'item_id' => 11531,
                'item_name' => 'hween_c20_duckgoddess',
                'prizes' => '11483:45;11530:45;11497:10',
                'required_effect' => 186,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            152 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11520,
                'item_name' => 'hween_r20_evilpandorabox',
                'prizes' => '11531:25;11498:25;11504:25;11502:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            153 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 30,
                'item_id' => 11502,
                'item_name' => 'hween_c20_eyedemon',
                'prizes' => '11537:45;11479:45;11506:10',
                'required_effect' => 162,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            154 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 30,
                'item_id' => 11504,
                'item_name' => 'hween_c20_octodemon',
                'prizes' => '11489:45;11494:45;11494:10',
                'required_effect' => 117,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            155 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 30,
                'item_id' => 11498,
                'item_name' => 'hween_c20_evilscarecrow',
                'prizes' => '11535:45;11492:45;11533:10',
                'required_effect' => 5,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            156 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11495,
                'item_name' => 'hween_c20_pandorabox',
                'prizes' => '10819:15;9761:13;10819:13;10789:10;8381:10;9186:10;10271:9;10271:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            157 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11562,
                'item_name' => 'plushie_c20_crackable',
                'prizes' => '11557:13;11556:13;11571:13;11599:13;11577:12;11563:12;11610:12;11588:12',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            158 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 11670,
                'item_name' => 'xmas_c20_runerock',
                'prizes' => '11659:20;11619:20;11664:20;11658:20;11642:20',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            159 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 11659,
                'item_name' => 'xmas_c20_runerockblue',
                'prizes' => '11619:25;11664:25;11658:25;11642:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            160 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 11619,
                'item_name' => 'xmas_c20_runerockgreen',
                'prizes' => '11659:25;11664:25;11658:25;11642:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            161 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 11664,
                'item_name' => 'xmas_c20_runerockpurple',
                'prizes' => '11659:25;11619:25;11658:25;11642:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            162 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 11658,
                'item_name' => 'xmas_c20_runerockred',
                'prizes' => '11659:25;11619:25;11664:25;11642:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            163 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 2,
                'item_id' => 11642,
                'item_name' => 'xmas_c20_runerockyellow',
                'prizes' => '11659:25;11619:25;11664:25;11658:25',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            164 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11738,
                'item_name' => 'bonusbag21_1',
                'prizes' => '11732:16;11733:16;11734:17;11735:17;11736:17;11737:17',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            165 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11739,
                'item_name' => 'bonusbag21_2',
                'prizes' => '11713:16;11714:16;11715:17;11716:17;11717:17;11718:17',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            166 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11731,
                'item_name' => 'bonusbag21_3',
                'prizes' => '11719:16;11720:16;11721:17;11722:17;11723:17;11724:17',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            167 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11712,
                'item_name' => 'bonusbag21_4',
                'prizes' => '11725:16;11726:16;11727:17;11728:17;11729:17;11730:17',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
            168 => 
            array (
                'achievement_cracked' => '',
                'achievement_tick' => '',
                'count' => 1,
                'item_id' => 11701,
                'item_name' => 'ny_r20_crackable',
                'prizes' => '11702:13;11703:13;11704:13;11705:13;11706:12;11707:12;11708:12;11709:12',
                'required_effect' => 0,
                'subscription_duration' => NULL,
                'subscription_type' => NULL,
            ),
        ));
        
        
    }
}