<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LogsShopPurchasesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('logs_shop_purchases')->delete();
        
        \DB::table('logs_shop_purchases')->insert(array (
            0 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1585,
                'catalog_name' => 'country_ditch',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 1,
                'item_ids' => '336',
                'points_type' => 0,
                'timestamp' => 1618369775,
                'user_id' => 3,
            ),
            1 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 8355,
                'catalog_name' => 'bonusrare16_1_2',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 2,
                'item_ids' => '337',
                'points_type' => 0,
                'timestamp' => 1618529560,
                'user_id' => 2,
            ),
            2 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60666,
                'catalog_name' => 'deal_COM_50bbtiles',
                'cost_credits' => 25,
                'cost_points' => 0,
                'id' => 3,
                'item_ids' => '388;387;386;385;384;383;382;381;380;379;378;377;376;375;374;373;372;371;370;369;368;367;366;365;364;363;362;361;360;359;358;357;356;355;354;353;352;351;350;349;348;347;346;345;344;343;342;341;340;339',
                'points_type' => 0,
                'timestamp' => 1618553019,
                'user_id' => 3,
            ),
            3 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3635,
                'catalog_name' => 'bb_gate_y',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 4,
                'item_ids' => '389',
                'points_type' => 0,
                'timestamp' => 1618553028,
                'user_id' => 3,
            ),
            4 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 6,
                'catalog_name' => 'rentable_bot_visitor_log',
                'cost_credits' => 35,
                'cost_points' => 0,
                'id' => 5,
                'item_ids' => '',
                'points_type' => 0,
                'timestamp' => 1618553110,
                'user_id' => 3,
            ),
            5 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 69265170,
                'catalog_name' => 'monsterseyes_c17_teaplant3',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 6,
                'item_ids' => '390',
                'points_type' => 0,
                'timestamp' => 1618705344,
                'user_id' => 3,
            ),
            6 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 99910862,
                'catalog_name' => 'calderos_sopas_name',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 7,
                'item_ids' => '391',
                'points_type' => 0,
                'timestamp' => 1618706371,
                'user_id' => 3,
            ),
            7 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 11744,
                'catalog_name' => 'china_c21_orangebasket',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 8,
                'item_ids' => '392',
                'points_type' => 0,
                'timestamp' => 1618706397,
                'user_id' => 3,
            ),
            8 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3730,
                'catalog_name' => 'qt_xm10_iceplasto',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 9,
                'item_ids' => '393',
                'points_type' => 0,
                'timestamp' => 1618706509,
                'user_id' => 3,
            ),
            9 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 65000569,
                'catalog_name' => 'easter_c20_stickteepee',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 10,
                'item_ids' => '394',
                'points_type' => 0,
                'timestamp' => 1618708137,
                'user_id' => 3,
            ),
            10 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 6492,
                'catalog_name' => 'bc_standinghalfcylinder_13',
                'cost_credits' => 2,
                'cost_points' => 0,
                'id' => 11,
                'item_ids' => '395',
                'points_type' => 0,
                'timestamp' => 1618708164,
                'user_id' => 3,
            ),
            11 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 5929,
                'catalog_name' => 'room_noob_wallbl1',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 12,
                'item_ids' => '396',
                'points_type' => 0,
                'timestamp' => 1618708188,
                'user_id' => 3,
            ),
            12 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 7881,
                'catalog_name' => 'room_gh15_cab3',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 13,
                'item_ids' => '397',
                'points_type' => 0,
                'timestamp' => 1618708225,
                'user_id' => 3,
            ),
            13 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 11290,
                'catalog_name' => 'gothiccafe_c20_bookcase',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 14,
                'item_ids' => '398',
                'points_type' => 0,
                'timestamp' => 1618710203,
                'user_id' => 3,
            ),
            14 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 69400799,
                'catalog_name' => 'table_plakfc_round',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 15,
                'item_ids' => '399',
                'points_type' => 0,
                'timestamp' => 1618710384,
                'user_id' => 3,
            ),
            15 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1567,
                'catalog_name' => 'a2 scifirocket',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 16,
                'item_ids' => '400',
                'points_type' => 0,
                'timestamp' => 1618756537,
                'user_id' => 3,
            ),
            16 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 50007,
                'catalog_name' => 'a0 pet7',
                'cost_credits' => 20,
                'cost_points' => 0,
                'id' => 17,
                'item_ids' => '',
                'points_type' => 0,
                'timestamp' => 1618762976,
                'user_id' => 3,
            ),
            17 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 5315,
                'catalog_name' => 'info_terminal',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 18,
                'item_ids' => '401',
                'points_type' => 0,
                'timestamp' => 1619014097,
                'user_id' => 3,
            ),
            18 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60355,
                'catalog_name' => 'poster 56',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 19,
                'item_ids' => '402',
                'points_type' => 0,
                'timestamp' => 1619014117,
                'user_id' => 3,
            ),
            19 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60386,
                'catalog_name' => 'poster 1004',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 20,
                'item_ids' => '403',
                'points_type' => 0,
                'timestamp' => 1619014121,
                'user_id' => 3,
            ),
            20 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 44110,
                'catalog_name' => 'ads_mtv_wall',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 21,
                'item_ids' => '404',
                'points_type' => 0,
                'timestamp' => 1619014410,
                'user_id' => 3,
            ),
            21 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 40290,
                'catalog_name' => 'tampax_wall',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 22,
                'item_ids' => '405',
                'points_type' => 0,
                'timestamp' => 1619014416,
                'user_id' => 3,
            ),
            22 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 65000573,
                'catalog_name' => 'easter_r20_mountaingoat',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 23,
                'item_ids' => '406',
                'points_type' => 0,
                'timestamp' => 1619014484,
                'user_id' => 3,
            ),
            23 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 227,
                'catalog_name' => 'a2 heart',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 24,
                'item_ids' => '409;410;407;408',
                'points_type' => 0,
                'timestamp' => 1619168724,
                'user_id' => 3,
            ),
            24 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60683,
                'catalog_name' => 'roombg_city2',
                'cost_credits' => 10,
                'cost_points' => 0,
                'id' => 25,
                'item_ids' => '411',
                'points_type' => 0,
                'timestamp' => 1619169040,
                'user_id' => 3,
            ),
            25 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60645,
                'catalog_name' => 'wallpaper_single_2804',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 26,
                'item_ids' => '412',
                'points_type' => 0,
                'timestamp' => 1619169237,
                'user_id' => 3,
            ),
            26 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60001,
                'catalog_name' => 'floor_single_502',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 27,
                'item_ids' => '413',
                'points_type' => 0,
                'timestamp' => 1619169265,
                'user_id' => 3,
            ),
            27 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60709,
                'catalog_name' => 'bling11_tele',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 28,
                'item_ids' => '415;414',
                'points_type' => 0,
                'timestamp' => 1619169408,
                'user_id' => 3,
            ),
            28 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60757,
                'catalog_name' => 'coralking_c18_shelltele',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 29,
                'item_ids' => '417;416',
                'points_type' => 0,
                'timestamp' => 1619169467,
                'user_id' => 3,
            ),
            29 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 68,
                'catalog_name' => 'A1 BM7',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 30,
                'item_ids' => '418',
                'points_type' => 0,
                'timestamp' => 1619169483,
                'user_id' => 3,
            ),
            30 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 68,
                'catalog_name' => 'A1 BM7',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 31,
                'item_ids' => '419;420',
                'points_type' => 0,
                'timestamp' => 1619169493,
                'user_id' => 3,
            ),
            31 => 
            array (
                'amount' => 8,
                'catalog_item_id' => 229,
                'catalog_name' => 'a2 heartsofa',
                'cost_credits' => 28,
                'cost_points' => 0,
                'id' => 32,
                'item_ids' => '428;427;426;425;424;423;422;421',
                'points_type' => 0,
                'timestamp' => 1619169507,
                'user_id' => 3,
            ),
            32 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1518,
                'catalog_name' => 'prizetrophy7_g',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 33,
                'item_ids' => '429',
                'points_type' => 0,
                'timestamp' => 1619169520,
                'user_id' => 3,
            ),
            33 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 187,
                'catalog_name' => 'present_gen',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 34,
                'item_ids' => '430',
                'points_type' => 0,
                'timestamp' => 1619169538,
                'user_id' => 3,
            ),
            34 => 
            array (
                'amount' => 3,
                'catalog_item_id' => 160,
                'catalog_name' => 'A1 ANANAS',
                'cost_credits' => 9,
                'cost_points' => 0,
                'id' => 35,
                'item_ids' => '433;432;431',
                'points_type' => 0,
                'timestamp' => 1619169554,
                'user_id' => 3,
            ),
            35 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1741,
                'catalog_name' => 'a0 lantern',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 36,
                'item_ids' => '434',
                'points_type' => 0,
                'timestamp' => 1619169566,
                'user_id' => 3,
            ),
            36 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 1741,
                'catalog_name' => 'a0 lantern',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 37,
                'item_ids' => '436;435',
                'points_type' => 0,
                'timestamp' => 1619169623,
                'user_id' => 3,
            ),
            37 => 
            array (
                'amount' => 8,
                'catalog_item_id' => 245,
                'catalog_name' => 'a1 armkp',
                'cost_credits' => 28,
                'cost_points' => 0,
                'id' => 38,
                'item_ids' => '442;439;438;437;440;441;444;443',
                'points_type' => 0,
                'timestamp' => 1619169641,
                'user_id' => 3,
            ),
            38 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 68,
                'catalog_name' => 'A1 BM7',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 39,
                'item_ids' => '445',
                'points_type' => 0,
                'timestamp' => 1619169745,
                'user_id' => 3,
            ),
            39 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 211,
                'catalog_name' => 'a2 menorah',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 40,
                'item_ids' => '447;446',
                'points_type' => 0,
                'timestamp' => 1619170008,
                'user_id' => 3,
            ),
            40 => 
            array (
                'amount' => 7,
                'catalog_item_id' => 91,
                'catalog_name' => 'A1 BV7',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 41,
                'item_ids' => '454;453;452;451;450;449;448',
                'points_type' => 0,
                'timestamp' => 1619170055,
                'user_id' => 3,
            ),
            41 => 
            array (
                'amount' => 3,
                'catalog_item_id' => 69,
                'catalog_name' => 'A1 BV2',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 42,
                'item_ids' => '457;456;455',
                'points_type' => 0,
                'timestamp' => 1619170058,
                'user_id' => 3,
            ),
            42 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 33,
                'catalog_name' => 'A1 BV1',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 43,
                'item_ids' => '458',
                'points_type' => 0,
                'timestamp' => 1619170061,
                'user_id' => 3,
            ),
            43 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 44520,
                'catalog_name' => 'jp_window',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 44,
                'item_ids' => '459;460',
                'points_type' => 0,
                'timestamp' => 1619170169,
                'user_id' => 3,
            ),
            44 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 1970,
                'catalog_name' => 'a2 china_table',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 45,
                'item_ids' => '462;461',
                'points_type' => 0,
                'timestamp' => 1619170219,
                'user_id' => 3,
            ),
            45 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 40060,
                'catalog_name' => 'a0 val_heart',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 46,
                'item_ids' => '463',
                'points_type' => 0,
                'timestamp' => 1619170322,
                'user_id' => 3,
            ),
            46 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 40370,
                'catalog_name' => 'DEV window_romantic_narrow',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 47,
                'item_ids' => '465;464',
                'points_type' => 0,
                'timestamp' => 1619170515,
                'user_id' => 3,
            ),
            47 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 1742,
                'catalog_name' => 'a0 rw_sofa',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 48,
                'item_ids' => '467;466',
                'points_type' => 0,
                'timestamp' => 1619170587,
                'user_id' => 3,
            ),
            48 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 3304,
                'catalog_name' => 'ads_twi_roses',
                'cost_credits' => 10,
                'cost_points' => 0,
                'id' => 49,
                'item_ids' => '469;468',
                'points_type' => 0,
                'timestamp' => 1619170625,
                'user_id' => 3,
            ),
            49 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1516,
                'catalog_name' => 'prizetrophy5_g',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 50,
                'item_ids' => '470',
                'points_type' => 0,
                'timestamp' => 1619170734,
                'user_id' => 3,
            ),
            50 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2606,
                'catalog_name' => 'sound_machine_pro',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 51,
                'item_ids' => '471',
                'points_type' => 0,
                'timestamp' => 1619170836,
                'user_id' => 3,
            ),
            51 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1,
                'catalog_name' => 'A2 tlp 20',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 52,
                'item_ids' => '499;498;497;496;495;494;500;492;491;490;484;493;489;488;487;486;485;501;483;482;481;480;479;478;477;476;475;474;473;472',
                'points_type' => 0,
                'timestamp' => 1619171032,
                'user_id' => 3,
            ),
            52 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 25,
                'catalog_name' => 'A1 LTP',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 53,
                'item_ids' => '502',
                'points_type' => 0,
                'timestamp' => 1619171085,
                'user_id' => 3,
            ),
            53 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 45940,
                'catalog_name' => 'val15_fujiwall',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 54,
                'item_ids' => '504;503',
                'points_type' => 0,
                'timestamp' => 1619171149,
                'user_id' => 3,
            ),
            54 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 47180,
                'catalog_name' => 'diamond_painting56',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 55,
                'item_ids' => '505',
                'points_type' => 0,
                'timestamp' => 1619171220,
                'user_id' => 3,
            ),
            55 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 42200,
                'catalog_name' => 'a2 slp',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 56,
                'item_ids' => '506',
                'points_type' => 0,
                'timestamp' => 1619171283,
                'user_id' => 3,
            ),
            56 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2698,
                'catalog_name' => 'sound_set_61',
                'cost_credits' => 2,
                'cost_points' => 0,
                'id' => 57,
                'item_ids' => '507',
                'points_type' => 0,
                'timestamp' => 1619171302,
                'user_id' => 3,
            ),
            57 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 232,
                'catalog_name' => 'a2 giftflowers',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 58,
                'item_ids' => '509;508',
                'points_type' => 0,
                'timestamp' => 1619171932,
                'user_id' => 3,
            ),
            58 => 
            array (
                'amount' => 3,
                'catalog_item_id' => 285,
                'catalog_name' => 'A0 raredaffodilrug',
                'cost_credits' => 15,
                'cost_points' => 0,
                'id' => 59,
                'item_ids' => '512;511;510',
                'points_type' => 0,
                'timestamp' => 1619172005,
                'user_id' => 3,
            ),
            59 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 2459,
                'catalog_name' => 'DEV rclr_sofa',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 60,
                'item_ids' => '514;513',
                'points_type' => 0,
                'timestamp' => 1619172058,
                'user_id' => 3,
            ),
            60 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1738,
                'catalog_name' => 'a0 snowrug',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 61,
                'item_ids' => '515',
                'points_type' => 0,
                'timestamp' => 1619172068,
                'user_id' => 3,
            ),
            61 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2982,
                'catalog_name' => 'xmas_snow',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 62,
                'item_ids' => '516',
                'points_type' => 0,
                'timestamp' => 1619172074,
                'user_id' => 3,
            ),
            62 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 294,
                'catalog_name' => 'A0 rarehammock',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 63,
                'item_ids' => '517',
                'points_type' => 0,
                'timestamp' => 1619172084,
                'user_id' => 3,
            ),
            63 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 279,
                'catalog_name' => 'a2 legobench',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 64,
                'item_ids' => '518',
                'points_type' => 0,
                'timestamp' => 1619172093,
                'user_id' => 3,
            ),
            64 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 160,
                'catalog_name' => 'A1 ANANAS',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 65,
                'item_ids' => '519',
                'points_type' => 0,
                'timestamp' => 1619172101,
                'user_id' => 3,
            ),
            65 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 4653,
                'catalog_name' => 'anc_comfy_tree',
                'cost_credits' => 14,
                'cost_points' => 0,
                'id' => 66,
                'item_ids' => '520;521',
                'points_type' => 0,
                'timestamp' => 1619172121,
                'user_id' => 3,
            ),
            66 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1587,
                'catalog_name' => 'a8 pillow',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 67,
                'item_ids' => '522',
                'points_type' => 5,
                'timestamp' => 1619172132,
                'user_id' => 3,
            ),
            67 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1629,
                'catalog_name' => 'a2 rare_icecream',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 68,
                'item_ids' => '523',
                'points_type' => 0,
                'timestamp' => 1619172164,
                'user_id' => 3,
            ),
            68 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2702,
                'catalog_name' => 'Brown Teddy',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 69,
                'item_ids' => '524',
                'points_type' => 0,
                'timestamp' => 1619172189,
                'user_id' => 3,
            ),
            69 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2700,
                'catalog_name' => 'Pink Teddy',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 70,
                'item_ids' => '525',
                'points_type' => 0,
                'timestamp' => 1619172192,
                'user_id' => 3,
            ),
            70 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1512,
                'catalog_name' => 'prizetrophy_g',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 71,
                'item_ids' => '526',
                'points_type' => 0,
                'timestamp' => 1619172225,
                'user_id' => 3,
            ),
            71 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1603,
                'catalog_name' => 'a10 wooden_screen',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 72,
                'item_ids' => '527',
                'points_type' => 0,
                'timestamp' => 1619172243,
                'user_id' => 3,
            ),
            72 => 
            array (
                'amount' => 3,
                'catalog_item_id' => 236,
                'catalog_name' => 'a2 bunny',
                'cost_credits' => 9,
                'cost_points' => 0,
                'id' => 73,
                'item_ids' => '528;529;530',
                'points_type' => 0,
                'timestamp' => 1619172259,
                'user_id' => 3,
            ),
            73 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2785,
                'catalog_name' => 'tiki_bflies',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 74,
                'item_ids' => '531',
                'points_type' => 0,
                'timestamp' => 1619172300,
                'user_id' => 3,
            ),
            74 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 45350,
                'catalog_name' => 'storieshero_poster',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 75,
                'item_ids' => '532',
                'points_type' => 0,
                'timestamp' => 1619172318,
                'user_id' => 3,
            ),
            75 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 40410,
                'catalog_name' => 'DEV window_romantic_wide',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 76,
                'item_ids' => '534;533',
                'points_type' => 0,
                'timestamp' => 1619172377,
                'user_id' => 3,
            ),
            76 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 193,
                'catalog_name' => 'present_gen6',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 77,
                'item_ids' => '535',
                'points_type' => 0,
                'timestamp' => 1619172548,
                'user_id' => 3,
            ),
            77 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 456,
                'catalog_name' => 'md_sofa',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 78,
                'item_ids' => '536',
                'points_type' => 0,
                'timestamp' => 1619172594,
                'user_id' => 3,
            ),
            78 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 456,
                'catalog_name' => 'md_sofa',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 79,
                'item_ids' => '537',
                'points_type' => 0,
                'timestamp' => 1619172609,
                'user_id' => 3,
            ),
            79 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60605,
                'catalog_name' => 'wallpaper_single_1501',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 80,
                'item_ids' => '538',
                'points_type' => 0,
                'timestamp' => 1619172773,
                'user_id' => 3,
            ),
            80 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60042,
                'catalog_name' => 'floor_single_208',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 81,
                'item_ids' => '539',
                'points_type' => 0,
                'timestamp' => 1619172796,
                'user_id' => 3,
            ),
            81 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60246,
                'catalog_name' => 'landscape_single_1.11',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 82,
                'item_ids' => '540',
                'points_type' => 0,
                'timestamp' => 1619172811,
                'user_id' => 3,
            ),
            82 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3039,
                'catalog_name' => 'bolly_palm',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 83,
                'item_ids' => '541',
                'points_type' => 0,
                'timestamp' => 1619172851,
                'user_id' => 3,
            ),
            83 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 10526,
                'catalog_name' => 'easter_c19_springtree',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 84,
                'item_ids' => '542',
                'points_type' => 0,
                'timestamp' => 1619172874,
                'user_id' => 3,
            ),
            84 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 1587,
                'catalog_name' => 'a8 pillow',
                'cost_credits' => 10,
                'cost_points' => 0,
                'id' => 85,
                'item_ids' => '544;543',
                'points_type' => 5,
                'timestamp' => 1619172977,
                'user_id' => 3,
            ),
            85 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1584,
                'catalog_name' => 'a9 pillow',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 86,
                'item_ids' => '545',
                'points_type' => 5,
                'timestamp' => 1619172982,
                'user_id' => 3,
            ),
            86 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 130,
                'catalog_name' => 'A1 BTP',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 87,
                'item_ids' => '547;546',
                'points_type' => 0,
                'timestamp' => 1619173027,
                'user_id' => 3,
            ),
            87 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 131,
                'catalog_name' => 'A1 BKP',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 88,
                'item_ids' => '548',
                'points_type' => 0,
                'timestamp' => 1619173033,
                'user_id' => 3,
            ),
            88 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 127,
                'catalog_name' => 'A2 BAP',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 89,
                'item_ids' => '549',
                'points_type' => 0,
                'timestamp' => 1619173037,
                'user_id' => 3,
            ),
            89 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 2022,
                'catalog_name' => 'a0 glass_sofa',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 90,
                'item_ids' => '553;552;551;550',
                'points_type' => 0,
                'timestamp' => 1619173052,
                'user_id' => 3,
            ),
            90 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 2020,
                'catalog_name' => 'a0 glass_chair',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 91,
                'item_ids' => '555;554',
                'points_type' => 0,
                'timestamp' => 1619173060,
                'user_id' => 3,
            ),
            91 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 8847,
                'catalog_name' => 'purablk_c16_lamp2',
                'cost_credits' => 6,
                'cost_points' => 0,
                'id' => 92,
                'item_ids' => '557;556',
                'points_type' => 0,
                'timestamp' => 1619173085,
                'user_id' => 3,
            ),
            92 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 146,
                'catalog_name' => 'A2 MURLOVE',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 93,
                'item_ids' => '558',
                'points_type' => 0,
                'timestamp' => 1619173094,
                'user_id' => 3,
            ),
            93 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 8949,
                'catalog_name' => 'jungle_c16_tree',
                'cost_credits' => 15,
                'cost_points' => 0,
                'id' => 94,
                'item_ids' => '559',
                'points_type' => 0,
                'timestamp' => 1619173129,
                'user_id' => 3,
            ),
            94 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 5755,
                'catalog_name' => 'nest_gnome',
                'cost_credits' => 2,
                'cost_points' => 0,
                'id' => 95,
                'item_ids' => '560',
                'points_type' => 0,
                'timestamp' => 1619173144,
                'user_id' => 3,
            ),
            95 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2109,
                'catalog_name' => 'a0 romantique_pianochair4',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 96,
                'item_ids' => '561',
                'points_type' => 0,
                'timestamp' => 1619173163,
                'user_id' => 3,
            ),
            96 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 75,
                'catalog_name' => 'A1 BV3',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 97,
                'item_ids' => '562',
                'points_type' => 0,
                'timestamp' => 1619173178,
                'user_id' => 3,
            ),
            97 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 90,
                'catalog_name' => 'A1 BV5',
                'cost_credits' => 2,
                'cost_points' => 0,
                'id' => 98,
                'item_ids' => '564;563',
                'points_type' => 0,
                'timestamp' => 1619173182,
                'user_id' => 3,
            ),
            98 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2102,
                'catalog_name' => 'A1 KYNTTILA1',
                'cost_credits' => 2,
                'cost_points' => 0,
                'id' => 99,
                'item_ids' => '565',
                'points_type' => 0,
                'timestamp' => 1619173196,
                'user_id' => 3,
            ),
            99 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2548,
                'catalog_name' => 'sound_machine7',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 100,
                'item_ids' => '566',
                'points_type' => 0,
                'timestamp' => 1619173207,
                'user_id' => 3,
            ),
            100 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3305,
                'catalog_name' => 'exe_elevator',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 101,
                'item_ids' => '568;567',
                'points_type' => 0,
                'timestamp' => 1619173253,
                'user_id' => 3,
            ),
            101 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3743,
                'catalog_name' => 'qt_xm10_icesilotable',
                'cost_credits' => 2,
                'cost_points' => 0,
                'id' => 102,
                'item_ids' => '569',
                'points_type' => 0,
                'timestamp' => 1619173279,
                'user_id' => 3,
            ),
            102 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 172,
                'catalog_name' => 'a2 ruusu',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 103,
                'item_ids' => '570',
                'points_type' => 0,
                'timestamp' => 1619173288,
                'user_id' => 3,
            ),
            103 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60529,
                'catalog_name' => 'wallpaper_single_215',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 104,
                'item_ids' => '571',
                'points_type' => 0,
                'timestamp' => 1619173310,
                'user_id' => 3,
            ),
            104 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60008,
                'catalog_name' => 'floor_single_602',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 105,
                'item_ids' => '572',
                'points_type' => 0,
                'timestamp' => 1619173323,
                'user_id' => 3,
            ),
            105 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 5536,
                'catalog_name' => 'roombg_city1',
                'cost_credits' => 10,
                'cost_points' => 0,
                'id' => 106,
                'item_ids' => '573',
                'points_type' => 0,
                'timestamp' => 1619173531,
                'user_id' => 3,
            ),
            106 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 43620,
                'catalog_name' => 'es_build1',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 107,
                'item_ids' => '574',
                'points_type' => 0,
                'timestamp' => 1619173547,
                'user_id' => 3,
            ),
            107 => 
            array (
                'amount' => 13,
                'catalog_item_id' => 45940,
                'catalog_name' => 'val15_fujiwall',
                'cost_credits' => 30,
                'cost_points' => 0,
                'id' => 108,
                'item_ids' => '587;586;585;584;583;582;581;580;579;578;577;576;575',
                'points_type' => 0,
                'timestamp' => 1619173590,
                'user_id' => 3,
            ),
            108 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 40270,
                'catalog_name' => 'a0 roomdimmer',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 109,
                'item_ids' => '588',
                'points_type' => 0,
                'timestamp' => 1619173693,
                'user_id' => 3,
            ),
            109 => 
            array (
                'amount' => 7,
                'catalog_item_id' => 227,
                'catalog_name' => 'a2 heart',
                'cost_credits' => 18,
                'cost_points' => 0,
                'id' => 110,
                'item_ids' => '591;595;594;593;592;589;590',
                'points_type' => 0,
                'timestamp' => 1619173792,
                'user_id' => 3,
            ),
            110 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 69,
                'catalog_name' => 'A1 BV2',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 111,
                'item_ids' => '599;598;597;596',
                'points_type' => 0,
                'timestamp' => 1619173806,
                'user_id' => 3,
            ),
            111 => 
            array (
                'amount' => 3,
                'catalog_item_id' => 90,
                'catalog_name' => 'A1 BV5',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 112,
                'item_ids' => '602;601;600',
                'points_type' => 0,
                'timestamp' => 1619173813,
                'user_id' => 3,
            ),
            112 => 
            array (
                'amount' => 8,
                'catalog_item_id' => 1585,
                'catalog_name' => 'a11 pillow',
                'cost_credits' => 35,
                'cost_points' => 0,
                'id' => 113,
                'item_ids' => '610;609;608;607;606;605;604;603',
                'points_type' => 5,
                'timestamp' => 1619173842,
                'user_id' => 3,
            ),
            113 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 125,
                'catalog_name' => 'A2 PL1',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 114,
                'item_ids' => '614;613;612;611',
                'points_type' => 0,
                'timestamp' => 1619173852,
                'user_id' => 3,
            ),
            114 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 94009202,
                'catalog_name' => 'popcorn',
                'cost_credits' => 16,
                'cost_points' => 0,
                'id' => 115,
                'item_ids' => '618;617;616;615',
                'points_type' => 0,
                'timestamp' => 1619173860,
                'user_id' => 3,
            ),
            115 => 
            array (
                'amount' => 7,
                'catalog_item_id' => 225,
                'catalog_name' => 'A2 KYNTTILAT2',
                'cost_credits' => 18,
                'cost_points' => 0,
                'id' => 116,
                'item_ids' => '625;624;623;622;619;620;621',
                'points_type' => 0,
                'timestamp' => 1619173875,
                'user_id' => 3,
            ),
            116 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3026,
                'catalog_name' => 'bolly_petals',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 117,
                'item_ids' => '626',
                'points_type' => 0,
                'timestamp' => 1619173921,
                'user_id' => 3,
            ),
            117 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60544,
                'catalog_name' => 'wallpaper_single_405',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 118,
                'item_ids' => '627',
                'points_type' => 0,
                'timestamp' => 1619173939,
                'user_id' => 3,
            ),
            118 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60037,
                'catalog_name' => 'floor_single_205',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 119,
                'item_ids' => '628',
                'points_type' => 0,
                'timestamp' => 1619173957,
                'user_id' => 3,
            ),
            119 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 285,
                'catalog_name' => 'A0 raredaffodilrug',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 120,
                'item_ids' => '629',
                'points_type' => 0,
                'timestamp' => 1619174124,
                'user_id' => 3,
            ),
            120 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 229,
                'catalog_name' => 'a2 heartsofa',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 121,
                'item_ids' => '631;630',
                'points_type' => 0,
                'timestamp' => 1619174142,
                'user_id' => 3,
            ),
            121 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 226,
                'catalog_name' => 'a2 statue',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 122,
                'item_ids' => '632',
                'points_type' => 0,
                'timestamp' => 1619174205,
                'user_id' => 3,
            ),
            122 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 3730,
                'catalog_name' => 'qt_xm10_iceplasto',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 123,
                'item_ids' => '636;635;634;633',
                'points_type' => 0,
                'timestamp' => 1619174246,
                'user_id' => 3,
            ),
            123 => 
            array (
                'amount' => 5,
                'catalog_item_id' => 285,
                'catalog_name' => 'A0 raredaffodilrug',
                'cost_credits' => 25,
                'cost_points' => 0,
                'id' => 124,
                'item_ids' => '642;639;640;638;641',
                'points_type' => 0,
                'timestamp' => 1619323363,
                'user_id' => 3,
            ),
            124 => 
            array (
                'amount' => 7,
                'catalog_item_id' => 285,
                'catalog_name' => 'A0 raredaffodilrug',
                'cost_credits' => 30,
                'cost_points' => 0,
                'id' => 125,
                'item_ids' => '649;648;647;646;645;644;643',
                'points_type' => 0,
                'timestamp' => 1619323395,
                'user_id' => 3,
            ),
            125 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 1,
                'catalog_name' => 'A2 tlp 20',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 126,
                'item_ids' => '669;668;667;666;665;664;663;662;661;660;659;658;657;656;655;654;653;652;651;650;679;678;677;676;675;674;673;672;671;670',
                'points_type' => 0,
                'timestamp' => 1619323449,
                'user_id' => 3,
            ),
            126 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 4698,
                'catalog_name' => 'roombg_mountains1',
                'cost_credits' => 15,
                'cost_points' => 0,
                'id' => 127,
                'item_ids' => '680',
                'points_type' => 0,
                'timestamp' => 1619323470,
                'user_id' => 3,
            ),
            127 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60682,
                'catalog_name' => 'roombg_city1',
                'cost_credits' => 10,
                'cost_points' => 0,
                'id' => 128,
                'item_ids' => '681',
                'points_type' => 0,
                'timestamp' => 1619323509,
                'user_id' => 3,
            ),
            128 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60544,
                'catalog_name' => 'wallpaper_single_405',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 129,
                'item_ids' => '682',
                'points_type' => 0,
                'timestamp' => 1619323546,
                'user_id' => 3,
            ),
            129 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60071,
                'catalog_name' => 'floor_single_406',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 130,
                'item_ids' => '683',
                'points_type' => 0,
                'timestamp' => 1619323568,
                'user_id' => 3,
            ),
            130 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 60071,
                'catalog_name' => 'floor_single_406',
                'cost_credits' => 1,
                'cost_points' => 0,
                'id' => 131,
                'item_ids' => '684',
                'points_type' => 0,
                'timestamp' => 1619323584,
                'user_id' => 3,
            ),
            131 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 43005279,
                'catalog_name' => 'saw_wibbofr_velo95',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 132,
                'item_ids' => '685',
                'points_type' => 0,
                'timestamp' => 1619323662,
                'user_id' => 3,
            ),
            132 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 6078,
                'catalog_name' => 'wildwest_sheriff',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 133,
                'item_ids' => '686',
                'points_type' => 0,
                'timestamp' => 1619323732,
                'user_id' => 3,
            ),
            133 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 6065,
                'catalog_name' => 'wildwest_saloon',
                'cost_credits' => 7,
                'cost_points' => 0,
                'id' => 134,
                'item_ids' => '687',
                'points_type' => 0,
                'timestamp' => 1619323748,
                'user_id' => 3,
            ),
            134 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 7999,
                'catalog_name' => 'room_info15_bus_2',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 135,
                'item_ids' => '688',
                'points_type' => 0,
                'timestamp' => 1619323869,
                'user_id' => 3,
            ),
            135 => 
            array (
                'amount' => 4,
                'catalog_item_id' => 456,
                'catalog_name' => 'md_sofa',
                'cost_credits' => 16,
                'cost_points' => 0,
                'id' => 136,
                'item_ids' => '689;692;691;690',
                'points_type' => 0,
                'timestamp' => 1619323984,
                'user_id' => 3,
            ),
            136 => 
            array (
                'amount' => 5,
                'catalog_item_id' => 4526,
                'catalog_name' => 'wl_wall2',
                'cost_credits' => 20,
                'cost_points' => 0,
                'id' => 137,
                'item_ids' => '697;696;695;694;693',
                'points_type' => 0,
                'timestamp' => 1619324076,
                'user_id' => 3,
            ),
            137 => 
            array (
                'amount' => 5,
                'catalog_item_id' => 4526,
                'catalog_name' => 'wl_wall2',
                'cost_credits' => 20,
                'cost_points' => 0,
                'id' => 138,
                'item_ids' => '702;701;700;699;698',
                'points_type' => 0,
                'timestamp' => 1619324123,
                'user_id' => 3,
            ),
            138 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 46110,
                'catalog_name' => 'diamond_painting7',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 139,
                'item_ids' => '703',
                'points_type' => 0,
                'timestamp' => 1619324364,
                'user_id' => 3,
            ),
            139 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 46420,
                'catalog_name' => 'xmas_c16_painting',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 140,
                'item_ids' => '704',
                'points_type' => 0,
                'timestamp' => 1619324371,
                'user_id' => 3,
            ),
            140 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 45500,
                'catalog_name' => 'diamond_painting3',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 141,
                'item_ids' => '705',
                'points_type' => 0,
                'timestamp' => 1619324382,
                'user_id' => 3,
            ),
            141 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 45480,
                'catalog_name' => 'diamond_painting5',
                'cost_credits' => 3,
                'cost_points' => 0,
                'id' => 142,
                'item_ids' => '706',
                'points_type' => 0,
                'timestamp' => 1619324388,
                'user_id' => 3,
            ),
            142 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3527,
                'catalog_name' => 'bw_boat',
                'cost_credits' => 5,
                'cost_points' => 0,
                'id' => 143,
                'item_ids' => '707',
                'points_type' => 0,
                'timestamp' => 1619324446,
                'user_id' => 3,
            ),
            143 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 3541,
                'catalog_name' => 'bw_water_2',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 144,
                'item_ids' => '709;708',
                'points_type' => 0,
                'timestamp' => 1619324482,
                'user_id' => 3,
            ),
            144 => 
            array (
                'amount' => 2,
                'catalog_item_id' => 3541,
                'catalog_name' => 'bw_water_2',
                'cost_credits' => 8,
                'cost_points' => 0,
                'id' => 145,
                'item_ids' => '711;710',
                'points_type' => 0,
                'timestamp' => 1619324527,
                'user_id' => 3,
            ),
            145 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2458,
                'catalog_name' => 'DEV rclr_garden',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 146,
                'item_ids' => '712',
                'points_type' => 0,
                'timestamp' => 1619324791,
                'user_id' => 3,
            ),
            146 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2562,
                'catalog_name' => 'DEV rclr_chair',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 147,
                'item_ids' => '713',
                'points_type' => 0,
                'timestamp' => 1619324797,
                'user_id' => 3,
            ),
            147 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 3109,
                'catalog_name' => 'eco_tree2',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 148,
                'item_ids' => '714',
                'points_type' => 0,
                'timestamp' => 1619324876,
                'user_id' => 3,
            ),
            148 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 65000570,
                'catalog_name' => 'easter_c20_waypointrocks',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 149,
                'item_ids' => '715',
                'points_type' => 0,
                'timestamp' => 1631580017,
                'user_id' => 7,
            ),
            149 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 65000570,
                'catalog_name' => 'easter_c20_waypointrocks',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 150,
                'item_ids' => '716',
                'points_type' => 0,
                'timestamp' => 1631580019,
                'user_id' => 7,
            ),
            150 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 190886,
                'catalog_name' => 'jaxos_casata2_name',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 151,
                'item_ids' => '717',
                'points_type' => 0,
                'timestamp' => 1631580209,
                'user_id' => 7,
            ),
            151 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 263,
                'catalog_name' => 'a2 kamera',
                'cost_credits' => 10,
                'cost_points' => 0,
                'id' => 152,
                'item_ids' => '718',
                'points_type' => 0,
                'timestamp' => 1631580605,
                'user_id' => 7,
            ),
            152 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 40270,
                'catalog_name' => 'a0 roomdimmer',
                'cost_credits' => 12,
                'cost_points' => 0,
                'id' => 153,
                'item_ids' => '719',
                'points_type' => 0,
                'timestamp' => 1631580615,
                'user_id' => 7,
            ),
            153 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 2742,
                'catalog_name' => 'traxgold',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 154,
                'item_ids' => '720',
                'points_type' => 0,
                'timestamp' => 1631581112,
                'user_id' => 7,
            ),
            154 => 
            array (
                'amount' => 1,
                'catalog_item_id' => 24952816,
                'catalog_name' => 'luxpillow3',
                'cost_credits' => 4,
                'cost_points' => 0,
                'id' => 155,
                'item_ids' => '721',
                'points_type' => 0,
                'timestamp' => 1631581308,
                'user_id' => 7,
            ),
        ));
        
        
    }
}