<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users_settings')->delete();
        
        \DB::table('users_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'credits' => 0,
                'achievement_score' => 0,
                'daily_respect_points' => 3,
                'daily_pet_respect_points' => 3,
                'respects_given' => 0,
                'respects_received' => 0,
                'guild_id' => 0,
                'can_change_name' => '0',
                'can_trade' => '1',
                'is_citizen' => '0',
                'citizen_level' => 0,
                'helper_level' => 0,
                'tradelock_amount' => 0,
                'cfh_send' => 0,
                'cfh_abusive' => 0,
                'cfh_warnings' => 0,
                'cfh_bans' => 0,
                'block_following' => '0',
                'block_friendrequests' => '0',
                'block_roominvites' => '0',
                'volume_system' => 100,
                'volume_furni' => 100,
                'volume_trax' => 100,
                'old_chat' => '0',
                'block_camera_follow' => '0',
                'chat_color' => 0,
                'home_room' => 0,
                'online_time' => 0,
                'tags' => 'Arcturus Emulator;',
                'club_expire_timestamp' => 0,
                'login_streak' => 0,
                'rent_space_id' => 0,
                'rent_space_endtime' => 0,
                'hof_points' => 0,
                'block_alerts' => '0',
                'talent_track_citizenship_level' => -1,
                'talent_track_helpers_level' => -1,
                'ignore_bots' => '0',
                'ignore_pets' => '0',
                'nux' => '0',
                'mute_end_timestamp' => 0,
                'allow_name_change' => '0',
                'perk_trade' => '0',
                'forums_post_count' => 0,
                'ui_flags' => 1,
                'has_gotten_default_saved_searches' => 1,
                'hc_gifts_claimed' => 0,
                'last_hc_payday' => 0,
                'max_rooms' => 50,
                'max_friends' => 300,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'credits' => 0,
                'achievement_score' => 23,
                'daily_respect_points' => 3,
                'daily_pet_respect_points' => 3,
                'respects_given' => 0,
                'respects_received' => 0,
                'guild_id' => 0,
                'can_change_name' => '0',
                'can_trade' => '1',
                'is_citizen' => '0',
                'citizen_level' => 0,
                'helper_level' => 0,
                'tradelock_amount' => 0,
                'cfh_send' => 0,
                'cfh_abusive' => 0,
                'cfh_warnings' => 0,
                'cfh_bans' => 0,
                'block_following' => '0',
                'block_friendrequests' => '0',
                'block_roominvites' => '0',
                'volume_system' => 100,
                'volume_furni' => 100,
                'volume_trax' => 100,
                'old_chat' => '0',
                'block_camera_follow' => '0',
                'chat_color' => 0,
                'home_room' => 0,
                'online_time' => 8037,
                'tags' => 'Arcturus Emulator;',
                'club_expire_timestamp' => 0,
                'login_streak' => 0,
                'rent_space_id' => 0,
                'rent_space_endtime' => 0,
                'hof_points' => 0,
                'block_alerts' => '0',
                'talent_track_citizenship_level' => 0,
                'talent_track_helpers_level' => -1,
                'ignore_bots' => '0',
                'ignore_pets' => '0',
                'nux' => '1',
                'mute_end_timestamp' => 0,
                'allow_name_change' => '0',
                'perk_trade' => '0',
                'forums_post_count' => 0,
                'ui_flags' => 1,
                'has_gotten_default_saved_searches' => 1,
                'hc_gifts_claimed' => 0,
                'last_hc_payday' => 0,
                'max_rooms' => 50,
                'max_friends' => 300,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 3,
                'credits' => 0,
                'achievement_score' => 73,
                'daily_respect_points' => 3,
                'daily_pet_respect_points' => 3,
                'respects_given' => 3,
                'respects_received' => 0,
                'guild_id' => 0,
                'can_change_name' => '0',
                'can_trade' => '1',
                'is_citizen' => '0',
                'citizen_level' => 0,
                'helper_level' => 0,
                'tradelock_amount' => 0,
                'cfh_send' => 0,
                'cfh_abusive' => 0,
                'cfh_warnings' => 0,
                'cfh_bans' => 0,
                'block_following' => '0',
                'block_friendrequests' => '0',
                'block_roominvites' => '0',
                'volume_system' => 100,
                'volume_furni' => 100,
                'volume_trax' => 100,
                'old_chat' => '0',
                'block_camera_follow' => '0',
                'chat_color' => 33,
                'home_room' => 0,
                'online_time' => 27367,
                'tags' => 'Arcturus Emulator;',
                'club_expire_timestamp' => 0,
                'login_streak' => 0,
                'rent_space_id' => 0,
                'rent_space_endtime' => 0,
                'hof_points' => 0,
                'block_alerts' => '0',
                'talent_track_citizenship_level' => 0,
                'talent_track_helpers_level' => -1,
                'ignore_bots' => '0',
                'ignore_pets' => '0',
                'nux' => '1',
                'mute_end_timestamp' => 0,
                'allow_name_change' => '0',
                'perk_trade' => '0',
                'forums_post_count' => 0,
                'ui_flags' => 1,
                'has_gotten_default_saved_searches' => 1,
                'hc_gifts_claimed' => 0,
                'last_hc_payday' => 0,
                'max_rooms' => 50,
                'max_friends' => 300,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 4,
                'credits' => 0,
                'achievement_score' => 0,
                'daily_respect_points' => 3,
                'daily_pet_respect_points' => 3,
                'respects_given' => 0,
                'respects_received' => 0,
                'guild_id' => 0,
                'can_change_name' => '0',
                'can_trade' => '1',
                'is_citizen' => '0',
                'citizen_level' => 0,
                'helper_level' => 0,
                'tradelock_amount' => 0,
                'cfh_send' => 0,
                'cfh_abusive' => 0,
                'cfh_warnings' => 0,
                'cfh_bans' => 0,
                'block_following' => '0',
                'block_friendrequests' => '0',
                'block_roominvites' => '0',
                'volume_system' => 100,
                'volume_furni' => 100,
                'volume_trax' => 100,
                'old_chat' => '0',
                'block_camera_follow' => '0',
                'chat_color' => 0,
                'home_room' => 0,
                'online_time' => 2631,
                'tags' => 'Arcturus Emulator;',
                'club_expire_timestamp' => 0,
                'login_streak' => 0,
                'rent_space_id' => 0,
                'rent_space_endtime' => 0,
                'hof_points' => 0,
                'block_alerts' => '0',
                'talent_track_citizenship_level' => -1,
                'talent_track_helpers_level' => -1,
                'ignore_bots' => '0',
                'ignore_pets' => '0',
                'nux' => '0',
                'mute_end_timestamp' => 0,
                'allow_name_change' => '0',
                'perk_trade' => '0',
                'forums_post_count' => 0,
                'ui_flags' => 1,
                'has_gotten_default_saved_searches' => 1,
                'hc_gifts_claimed' => 0,
                'last_hc_payday' => 0,
                'max_rooms' => 50,
                'max_friends' => 300,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 7,
                'credits' => 0,
                'achievement_score' => 0,
                'daily_respect_points' => 3,
                'daily_pet_respect_points' => 3,
                'respects_given' => 0,
                'respects_received' => 0,
                'guild_id' => 0,
                'can_change_name' => '0',
                'can_trade' => '1',
                'is_citizen' => '0',
                'citizen_level' => 0,
                'helper_level' => 0,
                'tradelock_amount' => 0,
                'cfh_send' => 0,
                'cfh_abusive' => 0,
                'cfh_warnings' => 0,
                'cfh_bans' => 0,
                'block_following' => '0',
                'block_friendrequests' => '0',
                'block_roominvites' => '0',
                'volume_system' => 100,
                'volume_furni' => 100,
                'volume_trax' => 100,
                'old_chat' => '0',
                'block_camera_follow' => '0',
                'chat_color' => 0,
                'home_room' => 0,
                'online_time' => 94,
                'tags' => 'Arcturus Emulator;',
                'club_expire_timestamp' => 0,
                'login_streak' => 0,
                'rent_space_id' => 0,
                'rent_space_endtime' => 0,
                'hof_points' => 0,
                'block_alerts' => '0',
                'talent_track_citizenship_level' => -1,
                'talent_track_helpers_level' => -1,
                'ignore_bots' => '0',
                'ignore_pets' => '0',
                'nux' => '1',
                'mute_end_timestamp' => 0,
                'allow_name_change' => '0',
                'perk_trade' => '0',
                'forums_post_count' => 0,
                'ui_flags' => 1,
                'has_gotten_default_saved_searches' => 1,
                'hc_gifts_claimed' => 0,
                'last_hc_payday' => 0,
                'max_rooms' => 50,
                'max_friends' => 300,
            ),
        ));
        
        
    }
}